name: RunTests

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - name: Install dependencies
        run: julia --project=test/ -e 'using Pkg; Pkg.instantiate()'
      - name: run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=test/ --code-coverage=user test/runtests.jl
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2